[package]
name = "clock"
version = "0.1.0"
authors = ["Beno√Æt Peccatte <benoit.peccatte@normation.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "*"
rppal = "*"
